apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiscal
  # O Argo CD geralmente roda no namespace 'argocd'
  namespace: argocd
  finalizers:
    # Garante que, se você deletar o root-app, todas as aplicações filhas também serão deletadas do cluster (Cascading Delete).
    # Para funcionar, as aplicações filhas também devem ter este finalizer configurado.
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default # Projeto padrão do Argo CD

  # 1. ORIGEM: Onde estão os manifestos no Git
  source:
    repoURL: "https://github.com/fabionaspolini/k8s-playground"
    targetRevision: main # Branch, tag ou commit (ex: main, v1.0)
    path: helm-charts/whoami # Pasta dentro do repositório onde estão os YAMLs do K8s
    helm:
      valueFiles:
        - ../../04-argocd-gitops/manifests/fiscal/custom-values.yaml

  # 2. DESTINO: Para onde o Argo CD vai enviar os recursos
  destination:
    server: "https://kubernetes.default.svc" # O próprio cluster onde o Argo CD está rodando
    namespace: teste-argocd-v4 # Namespace de destino do seu app

  # 3. POLÍTICA DE SINCRONIZAÇÃO
  syncPolicy:
    automated:
      enabled: true # Enables automated syncing of the application ( true by default ).
      prune: true # Remove do K8s recursos que você apagou do Git - Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Se alguém alterar o cluster manualmente, o Argo CD sobrescreve com o que está no Git - Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: true # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=true # Cria o namespace 'teste-argocd-v4' caso ele não exista
