apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  # namespace: teste
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "2Mi"
              cpu: "2m"
            limits:
              memory: "32Mi"
              cpu: "25m"
