apiVersion: v1
kind: Service
metadata:
  name: whoami
  # namespace: teste # Deve estar no mesmo namespace
spec:
  selector:
    app: whoami # Deve bater exatamente com o label do Deployment
  # type: NodePort
  ports:
    - protocol: TCP
      port: 80 # Porta exposta pelo Service
      targetPort: 80 # Porta onde o container está rodando
